# Generated by Django 4.0.5 on 2022-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calented_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calevent',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
