# Generated by Django 4.0.5 on 2022-07-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calented_api', '0002_calevent_date_calevent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calevent',
            name='time',
        ),
        migrations.AlterField(
            model_name='calevent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
