# Generated by Django 4.0.5 on 2022-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calented_api', '0003_remove_calevent_time_alter_calevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calevent',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
