# Generated by Django 4.0.5 on 2022-07-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calented_api', '0004_calevent_time_alter_calevent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calevent',
            name='date_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
